import os
from dotenv import load_dotenv

load_dotenv() ## to load the azure credentials

IMAGE_RESOLUTION_SCALE = 2.0

## PDF PARSING
PDF_PARSING_METHOD = 'docling'
NON_REDUNDANT_PICTURE_SET_CHUNKING_SIZE = 5
GENERATE_PAGE_IMAGES = True
GENERATE_PICTURE_IMAGES = True
GENERATE_TABLE_IMAGES = True

## EXTRACTED OUTPUT PATH

EXTRACTED_OUTPUT_ROOT = "extracted_output"
EXTRACTED_PDF_FILE_OUTPUT_ROOT_FOLDER = f"\\{EXTRACTED_OUTPUT_ROOT}\\pdf\\"
EXTRACTED_PPTX_FILE_OUTPUT_ROOT_FOLDER = f"\\{EXTRACTED_OUTPUT_ROOT}\\pptx\\"
WORD_DOCUMENT_FINAL_OUTPUT_PATH = '\\output_summary\\docx\\final\\'
MARKDOWN_INDIVIDUAL_PAGES_FROM_PPTX_PAGES_OUTPUT_PATH = '\\output_summary\\markdown\\pptx_pages_converted_to_markdown\\'
MARKDOWN_DOCUMENT_FINAL_OUTPUT_PATH = '\\output_summary\\markdown\\final\\'

## TRIAGING VARIABLES
BASE64_ENCODING_AUTO_SHAPE_TRIAGING = 15
BASE64_ENCODING_CHART_TRIAGING = 1
BASE64_ENCODING_LINE_TRIAGING = 1
BASE64_ENCODING_DIAGRAM_TRIAGING = 1
BASE64_ENCODING_CANVAS_TRIAGING = 1
BASE64_ENCODING_MATH_SHAPE_TRIAGING = 2
BASE64_ENCODING_PICTURE_TRIAGING = 4
BASE64_ENCODING_SECTION_HEADER_TRIAGING = 6 # FOR PDF number of section headers that triggers base64 encoding of pdf pages for knowledge extraction

## PICTURE REDUNDANCY ANALYSIS VARIABLES
PICTURE_SIMILARITY = 90
REDUNDANCY_PRESENCE_THRESHOLD = 0.30
ALPHA = 0.6 # BALANCING BETWEEN OVERLAP AND DISTANCE TO IDENTIFY PICTURES THAT ARE "REDUNDANT"

## COMPRESSION PARAMETERS

IMAGE_COMPRESSION_QUALITY = 95
IMAGE_COMPRESSION_MAX_WIDTH = 896  # Resize to max width
IMAGE_COMPRESSION_MAX_HEIGHT= 504  # Resize to max height
IMAGE_COMPRESSION_FORMAT = "JPEG"

## AZURE OPEN AI CREDENTIALS
API_KEY = os.environ["AZURE_OPENAI_API_KEY"]
API_VERSION = os.environ["AZURE_OPENAI_API_VERSION"]
AZURE_OPENAI_ENDPOINT = os.environ["AZURE_OPENAI_ENDPOINT"]
AZURE_OPENAI_MODEL_NAME = os.environ["AZURE_OPENAI_MODEL_NAME"]
AZURE_OPENAI_MODEL = os.environ["AZURE_OPEN_AI_MODEL"]
CONTEXT_WINDOW_LIMIT = int(os.environ["CONTEXT_WINDOW_LIMIT"])

## MODEL PARAMETERS 
MAX_TOKEN_COMPLETION = 4000 ## 4000 was for GPT4o we will need to make this dynamic in function of the model
TEMPERATURE = 0 # should be made dynamic in function of task or model

## DOCLING MODEL

DOCLING_TRANSFORMER_MODEL_PATH = "<define where your local transformer for docling is>"